name: iOS Export IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4 # به v4 تغییر یافت

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build iOS App (Unsigned)
        run: |
          flutter build ios --release --no-codesign

      - name: Create IPA (Manual Archive)
        run: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload
          zip -r Runner.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4 # به v4 تغییر یافت
        with:
          name: ios-ipa
          path: Runner.ipa